spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:D:/IT/StudiaPodyplomowe/enroller-backend/enroller-db'
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
